### ISSUE TITLE
Serialize the data when it is coming from web sockets

### ISSUE THREAD

**Issue by ghoshnirmalya** [wopian/kitsu#121]
When I use the api of Kitsu to fetch data, it works fine. I was wondering if there is a way to serialize the data when it's coming from web sockets. Does Kitsu have any api whereby I can only serialize the data?

**Comment by wopian** [comment]
The internal functions aren't exposed currently.

May be a good idea to split all of the internal functions into a separate package (e.g `kitsu-core`) which would then allow what you need.

**Comment by ghoshnirmalya** [comment]
Splitting the internal functions into a separate package makes sense here. If they are exposed, I can serialize the data coming from web sockets as well!

**Comment by wopian** [comment]
Exposing the internal functions in https://github.com/wopian/kitsu/issues/125

**Comment by wopian** [comment]
`kitsu-core` is now on [npm](https://www.npmjs.com/package/kitsu-core) with the `5.0.0` release 🎉
