### ISSUE TITLE
Prevent infinite relationship nesting loop

### ISSUE THREAD

**Issue by spawnia** [wopian/kitsu#133]
All is fine if i make such a request:
````javascript
this.api.get('printers', {
      include: 'paper',
    })
````

This works as well:
````javascript
this.api.get('printers', {
      include: 'labels',
    })
````

And this returns 400 Bad Request:
````javascript
this.api.get('printers', {
      include: 'labels,nonexistinginclude',
    })
````

But this causes to client to freeze, the Browsertab becomes unresponsive and i have to close it:
````javascript
this.api.get('printers', {
      include: 'paper,labels',
    })
````

I tried sending the request from elsewhere, no problem whatsoever. Maybe Kitsu can not deal with multiple includes?

**Comment by wopian** [comment]
Are you able to provide the response it's receiving? I can't replicate this issue in the demo on codepen: https://codepen.io/wopian/pen/RxmEeK

**Comment by spawnia** [comment]
I put up a Mock API to test on: http://demo9418135.mockable.io/printers?include=paper,labels

The problem may be related to using a plural include (labels) and a singular include (paper) in the same request. *paper* actually refers to a resource with the type *papers*.

**Comment by wopian** [comment]
You'd need to give it the `HTTPS` address (`https://demo9418135.mockable.io/printers?include=paper,labels`) for the request to be sent. You wont be able to as it's crashing the tab milliseconds after `kitsu` receives the response. Its a somewhat major issue with how the relationships are deserialised. 

---

The response you've provided has the included `papers` and `labels` also include their own relationships. Which in this case refers to the root `printers` and the included `papers` and `labels`. 

While this is a valid JSON:API structure, it is not a valid response for the query provided. The `include=paper,labels` query should only have `printers`' relationships resolved. The included `paper` and `labels` relationships should just contain the links (below). 

```js
{
  relationships: {
    paper: {
      links: { self: '', related: '' }
    }
  }
}
```

`include=paper.labels,labels.paper,labels.printers` would be a request that should genuinely run into this bug.

This is causing `kitsu` to infinitely nest the relationships into the parent `printers` resource, i.e:

```js
{
  data: {
    type: 'printers',
    paper: {
      labels: [
        paper: { labels [ /* infinitely nest papers and printers */ ] },
        printers: [ { /* infinitely nest root data structure again */ } ]
      ],
    },
    labels: [
      paper: { labels [ /* infinitely nest papers and printers */ ] },
      printers: [ { /* infinitely nest root data structure again */ } ]
    ]
  }
}
```

Which quite quickly locks up the runtime in what's basically a DOS attack. Less of an issue in browsers as they can detect and kill the process when this happens. In node it killed my distro.

**Comment by nanawel** [comment]
Hi there,
is this bug being working on? I have a similar situation where relationships can sometimes create loops and it breaks the browser when the page loads (FF and Chromium).
I don't know how to fix this on the server-side because basically the structure is valid and really reflects the relationships between my entities.

**Comment by wopian** [comment]
Not being actively looked into at the moment. PRs are welcome in the meantime however.

Possible solutions 
1. Limit nesting depth. Nerfs the usability for deeply nested relationships that aren't infinitely looping.
2. Abort when the the same relationship object is added in a relationship chain (e.g user 1 -> libraryEntry 1 -> user 1
3. Additional parameter to Kitsu class and/or per-request to keep included relationships inside the `included` array.
	- Fixes the issue for those aware of the parameter
	- Package will still explode if an unaware user requests a resource that causes infinite nesting.

**Comment by Ouadie** [comment]
Is it possible to use another deserializer eg. https://github.com/weilandia/deserialize-json-api instead of kitsu-core one to prevent this issue?

**Comment by fspoettel** [comment]
Is this still an issue now after #601 landed?

**Comment by wopian** [comment]
> Is this still an issue now after #601 landed?

Nope, #601 should have fixed this issue and appears to have done in the circular relationship tests I've written
