### ISSUE TITLE
Is it possible to give filters names ?

### ISSUE THREAD

**Issue by drupalshift** [wopian/kitsu#148]
Is it possible to filter like this : 

`?filter[myfilter][condition][path]=field_page.name&filter[myfilter][condition][value]=home`

I tried several objects and arrays in filter but had no chance

**Comment by wopian** [comment]
Multiple filters for the same property/filter kind isn't currently possible with this package at the moment 😞

**Comment by wopian** [comment]
Fixed in `6.0.0`
