### ISSUE TITLE
kitsu and kitsu-core are uploaded to the npm registry with wrong directory permissions

### ISSUE THREAD

**Issue by etamponi** [wopian/kitsu#152]
I use [pnpm](https://github.com/pnpm/pnpm) as my package manager, and I can't install kitsu nor kitsu-core because the file uploaded to the npm registry has the wrong directory permissions. You can try it yourself:

http://registry.npmjs.org/kitsu/-/kitsu-5.0.6.tgz

untar it and try to enter the directory: you won't be able to `cd` into it (at least on macOS and on Linux).

I've [already asked](https://github.com/npm/registry/issues/293) in the npm registry issue tracker and they suggest to solve this by releasing a new patch version with the fix.

Can you please do it? Thanks in advance!

**Comment by wopian** [comment]
Directories and files are stored as `775` and `644` respectively, so I don't know where the directories are getting mutated into `644` while untarring.

It installs without issue with both `npm` and `yarn` (`kitsu` and `kitsu-core` in `node_modules` has directories/files as `775` and `644`) so looks like it may be an issue with `pnpm` itself.

**Comment by etamponi** [comment]
No, it's not simply an issue with pnpm, as you can see by downloading the tar file above: the directories are set to 644. pnpm can be patched to make sure all directories have the `x` flag, but the real fix here is figuring out why the package is being created with the wrong directory permissions, I believe. This is also what the people at the npm registry repo suggest.

**Comment by etamponi** [comment]
Just suggesting... perhaps you're running `npm publish` as root?

**Comment by wopian** [comment]
`yarn publish` is run under 2 different users with non-root privileges. Can you try `5.0.7`?

**Comment by wopian** [comment]
Laptop had an erroneous `umask` set. Having set it back to the correct value, the tarball created is now identical on both devices again :+1:

**Comment by etamponi** [comment]
Thank you!!! :)
