### ISSUE TITLE
Is it possible to filter includes ?

### ISSUE THREAD

**Issue by Cleverdawn** [wopian/kitsu#161]
I'd like to filter Library entries of a user to get a list of his completed TV (anime.showType) anime x)
As of now I'm not filtering on showType. 

https://stackoverflow.com/questions/40204854/json-api-filter-included-resources

In fact I want a random completed TV anime of a user library entries x). I'm currently doing that through 3 requests right now :/
First to get user ID, second to get library entries number of completed animes of this user (found in meta), and third to get the said random anime (with page offset limit 1).

**Comment by wopian** [comment]
This isn't the right place for this (it would be better in [hummingbird-me/hummingbird](https://github.com/hummingbird-me/hummingbird) or [kitsu.io/feedback](https://kitsu.io/feedback/))

However the accepted answer given in that stackoverflow post is incorrect - the answer below it is correct in that JSON:API Resources (the JSON:API library Kitsu.io uses) doesn't support filtering of includes.

So the 3 requests you're doing is probably the best you can do at the moment, as you can't filter by `subtype` with the request below (which would still require a request to get the total number)

https://kitsu.io/api/edge/library-entries?filter[user_id]=42603&filter[status]=completed&filter[kind]=anime&page[limit]=1&include=media

**edit:** `showType` is also deprecated - use `subtype`
