### ISSUE TITLE
Possible to get data for season and year through API?

### ISSUE THREAD

**Issue by daffychuy** [wopian/kitsu#175]
Is it possible to get the season and its year of a particular anime from the API? I see everything but the season.

**Comment by wopian** [comment]
While you can filter by season (`filter[season]=spring&filter[season_year]=2018` etc), there is no field specifically for it, as its simply generated from the `startDate`.

Winter: Dec-Feb
Spring: Mar-May
Summer: Jun-Aug
Autumn: Sep-Nov

Tests for Kitsu's API: https://github.com/hummingbird-me/hummingbird-server/blob/ed15fef20c044b0cd534dbc1ed054b10a5f821eb/spec/models/anime_spec.rb#L65
Kitsu's client implementation: https://github.com/hummingbird-me/hummingbird-client/blob/50e4bc467a575f6cef05a2d8393ff42cf5c51506/app/components/media/media-information.js#L24
