### ISSUE TITLE
TypeScript Declarations

### ISSUE THREAD

**Issue by wopian** [wopian/kitsu#220]
`6.4.0` added auto generated declaration files with `any` type for the exported functions' arguments. Ideally this should be fully typed with the expected types from the [JSDoc](http://usejsdoc.org/index.html) comments.

Once this is complete, IDEs (such as Visual Studio Code's Intellisense) will be able to provide the structure and documentation to developers as they use this library in their own code.

### What needs doing

As this is not (and won't be) a TypeScript project, these will have to be manually modified. The generated declarations were made with [dts-gen](https://github.com/Microsoft/dts-gen) and has correctly listed the two package's structure with their public functions. 

These need:
- The function's argument names and types added instead of the `...args: any[]` placeholder.
  - :information_source: [Do's & Don'ts](
https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html) for typings.
  - :warning: Arguments that accept multiple types should have the `any` type
- The function's return type
  - :warning: If the JSDoc does not specify the return type but does use the `return` keyword in the code, keep it as `any`.

The documentation for each package is in the same file the function is declared in, so searching for the function name will give you the required documentation.

### TypeScript Declarations

- [`packages/kitsu/index.d.ts`](https://github.com/wopian/kitsu/blob/master/packages/kitsu/index.d.ts)
- [`packages/kitsu-core/index.d.ts`](
https://github.com/wopian/kitsu/blob/master/packages/kitsu-core/index.d.ts)

### Useful Resources

https://blogs.msdn.microsoft.com/typescript/2016/12/14/writing-dts-files-for-types/
https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html
http://definitelytyped.org/guides.html

**Comment by hiteshpr** [comment]
I can work on this.

**Comment by wopian** [comment]
@hiteshpr awesome! I've just fixed the failing tests on the master branch - there were some breaking changes I was doing a few weeks ago that should've been in a pull request (#226) instead.

**Comment by hiteshpr** [comment]
@wopian Can you add more description about the issue and what needs to be done.

**Comment by nionoku** [comment]
I'm currently working on the current task, and I have a question. For example, now in TypeScript we can call the method this way:

`const animeList: Categories = await new Kitsu().get<Categories>({ resource: 'anime', resourceId: 2, relationship: 'categories' })`

It does not look very nice in terms of casting.
Is it possible to add the following mechanism for auto-typing in your library's api? The call will look like this:

`const animeCategories: Categories[] = await new Kitsu()`
`    .anime(2)  // 2 - is resourceId`
`    .categories()`
`    .get();`

Or example for get anime with id 70:

`const anime: Anime = await new Kitsu()`
`    .anime(70)`
`    .get();`

or is it better to create a separate project with the proposed implementation (called, for example, `kitsu-types`) for these purposes?

**Comment by nionoku** [comment]
> It'd be better as a separate project @nionoku

Ok. I would be interested to deal with this problem.

> as those changes would restrict this to just Kitsu.io (and requiring updates if new resources/relations are added) whereas it currently works with any JSON:API API endpoint.

You're right, but for a quality type-cast, this is a good option.

According to the results I will inform here.
