### ISSUE TITLE
Bumping to 7.0.1 results in "export 'deserialise' was not found in 'kitsu-core'

### ISSUE THREAD

**Issue by weilandia** [wopian/kitsu#292]
Hi 👋 

Not seeing an obvious change that caused this, but upgrading to 7.0.1 breaks my `deserialise` imports:

`"export 'deserialise' was not found in 'kitsu-core'`

**Comment by wopian** [comment]
Should be fixed in 7.0.2. 

Node 11 picked up `.mjs` files if they existed (so package.json had `/lib` as the path for CommonJS and ES Modules. In Node 12 this no longer happens (so it was trying to find an ESM export in a CJS file)

**Comment by weilandia** [comment]
Thanks!
