### ISSUE TITLE
double filter

### ISSUE THREAD

**Issue by tim-fastpay** [wopian/kitsu#316]
how could I write this code with Kitsu?

`filter[lte][postingDate]=endDate`

**Comment by tim-fastpay** [comment]
found answer

			api.get('url', {
				filter: {
					lte: {
						postingDate: endDate
					}
				}
			})

**Comment by wopian** [comment]
Added to Quick Start in 9.0.3

**Comment by patrickcate** [comment]
Was this ever added to the docs?

**Comment by wopian** [comment]
> Was this ever added to the docs?

An example for filtering (and other JSON:API parameters) was added to the Quick Start with a link to JSON:API's specification for filtering in the documentation (it's agnostic to the kind of filtering, like this package, so impossible to fully document without overburdening consumers with server-specific features that do not work with the API I use for working examples)

I've added a dedicated example for nested filters under `get`'s documentation as it is now officially part of the [JSON:API specification for filtering in 1.1](https://jsonapi.org/format/1.1/#query-parameters-families)
