### ISSUE TITLE
Cookies ommitted?

### ISSUE THREAD

**Issue by glebmikulko** [wopian/kitsu#334]
It seems like `kitsu` omits my cookies (session) data. Why?

**Comment by glebmikulko** [comment]
Is there any possibility to set `axios.defaults.withCredentials = true`?

**Comment by wopian** [comment]
You should be able to mutate the axios defaults for the instance `kitsu` creates using `kitsu.axios.defaults.withCredentials = true` (with kitsu = new Kitsu())

Will add option to set axios options in the constructor (no idea why I hard coded timeout only)

**Comment by wopian** [comment]
```js
new Kitsu(axiosOptions: { withCredentials: true })
``` 
is available in 7.1.0
