### ISSUE TITLE
Axios 0.19.1

### ISSUE THREAD

**Issue by glebmikulko** [wopian/kitsu#356]
Is there any chance to update `axios` dependency to the latest version? https://github.com/axios/axios/commit/960e1c879892ac6e1c83a798c06b9907e35ad2df

**Comment by wopian** [comment]
It is already using the latest `axios` (^0.19.0 matches 0.19.1).

A simple `yarn upgrade` or `npm update --save` in your project will give you 0.19.1 👍

**Comment by glebmikulko** [comment]
My bad, thanks for correcting
