### ISSUE TITLE
how to send raw request?

### ISSUE THREAD

**Issue by gadelkareem** [wopian/kitsu#414]
Is there a way to send a raw request? for ex I used to do something like this with https://github.com/twg/devour:
```
api.runMiddleware({
      url: api.apiUrl + '/users/' + id + '/password',
      method: 'PATCH',
      data,
      model: 'update-password-request'
})
```

**Comment by gadelkareem** [comment]
No it is a jsonapi request but with a custom URL

**Comment by wopian** [comment]
There's nothing explicitly built-in to do that (middleware would be a good feature request to make).

However the Axios instance is exposed so you can construct a custom PATCH request yourself using the methods from `kitsu-core`.

E.g:

```js
import Kitsu from 'kitsu'
import { serialise, deserialise } from 'kitsu-core'

const api = new Kitsu({ baseURL: 'https://example.com' })

const updatePassword = async (body) => {
  const { data } = await api.axios.patch(
	`users/${body.id}/password`, // Sends request to https://example.com/users/1/password
  	serialise('myModelType', body)
  )
  return deserialise(data)
}

updatePassword({ id: '1', password: 'myPassword' })

**Comment by wopian** [comment]
Although, deprecating the automatic extraction of `type` and `id` from the model parameter (first param of api.patch) _would_ make it a plain URL. With the `id` and `type` attributes defined in the body parameter (second). Fully supporting this issue and arguably simplifying the library code.

Another weird choice I made years ago and yet another major breaking change if I go ahead with this in the future.

**Comment by wopian** [comment]
Moved this to #415 to discuss this change further. With changes proposed in #415 the code in OP would be the following with `kitsu`:

```js
api.patch(`users/${id}/password`, data)
```

**Comment by gadelkareem** [comment]
Thanks a lot for the quick answer. I think sending an object would simplify the call so I wonder if something like this would work?
```
api.rawRequest = async (payload) => {
  const { data } = await api.axios.request({
    method: payload.method,
    url: payload.url,
    data: api.serialise(payload.model, payload.body)
  })
  return api.deserialise(data)
}
```

**Comment by wopian** [comment]
Added in e8aacc5ba6a98a1bfeb9ca02df30c20a90ac5167

Documentation will be at https://github.com/wopian/kitsu/tree/master/packages/kitsu#request once it's released. 

Until then, example usage is available in the JSDoc comments here: https://github.com/wopian/kitsu/blob/master/packages/kitsu/src/index.js#L366-L423

E.g
```js
api.request({
  method: 'PATCH',
  url: 'anime',
  type: 'anime',
  body: { id: '1', subtype: 'tv' }
})
```

**Comment by wopian** [comment]
Released in `9.1.0`

**Comment by gadelkareem** [comment]
@wopian I see the tests are passing but I still cannot call it from my app. I also do not see the declaration in the index.d.ts

**Comment by gadelkareem** [comment]
never mind it is working now

**Comment by wopian** [comment]
> I also do not see the declaration in the index.d.ts

I forgot to update the TypeScript definitions for the past few releases. 

They're now updated during release (thanks to TS 3.7 supporting JSDoc) and I've improved the documentation to give TS users much better type information.
