### ISSUE TITLE
Serialise any valid JSON in attributes

### ISSUE THREAD

**Issue by matt-l-w** [wopian/kitsu#430]
Hello,

This is a *feature request*.

Currently, the serialiser attempts extract data that _should_ live in the relationships section and set the attributes to the remainder of the info (type, id). This prevents you from sending anything other than resources as attributes.

In the [JSONAPI spec for attributes](https://jsonapi.org/format/#document-resource-object-attributes) it says that
> Attributes may contain any valid JSON value.

It would be great to conform to the spec and allow any information to be placed in the attributes.

## Problems
As far as I can see, this doesn't present any major issues other than a redesign of some of the methods in the (de)serialiser. I might suggest that we, instead, check for the `type` attribute of any objects that appear and use that as the identifier for whether to extract to relationships or not. Would love to know if you have any better suggestions (you'll be able to guess the ramifications far better than I can!)

**Comment by wopian** [comment]
Sorry, looks like I screwed the release of `9.0.0` by forgetting to commit the breaking changes in `deserialise` to the `serialise` function.

I was pretty busy at the time so I must've just left it for the next day and forgot I hadn't done it yet 
 as I had already documented the new behaviour.

The intended input/output is supposed to be the opposite of this example in the v9 migration docs: https://github.com/wopian/kitsu/blob/master/packages/kitsu/MIGRATING.md#new-behaviour

**Comment by wopian** [comment]
This should be fixed in `10.0.0-alpha.0`. Apologies for the delay in response...I really need to find a GitHub action to auto-assign myself 😢

**Comment by matt-l-w** [comment]
No apologies needed! Thanks for sorting it all out and maintaining this repo.
