### ISSUE TITLE
Deserialise relationships should not have data attribute

### ISSUE THREAD

**Issue by svengau** [wopian/kitsu#514]
Hello and thanks for this great library!

I've noticed a small nit: according [the doc sample](https://github.com/wopian/kitsu/tree/master/packages/kitsu-core#deserialise), `deserialise` result should be:
`{ data: { id: '1', user: { type: 'users', id: '2', slug: 'wopian' } } }`

but in fact, it's:
`{ data: { id: '1', user: {data: { type: 'users', id: '2', slug: 'wopian' } } } }`

I've checked the tests, and indeed, the 2nd format is used there. In my humble opinion, we should stick to the format in the doc sample, because it provides the same result for bot relationship and embedded object. The frontend dev doesn't have to know if an object has been marked as an embedded object or a relationship, aka he should not deal with json:api internal transport layer.

WDYT?

**Comment by revgum** [comment]
I suspect you're seeing outdated documentation.. I noticed the same big change when we migrated from 7x to 9x, there was a breaking change at 8x that added the data in the relationships. https://github.com/wopian/kitsu/blob/master/packages/kitsu/MIGRATING.md

Personally, I would have liked to avoid the `data` with nested relationships, but it wasn't a huge ordeal for our use.

**Comment by wopian** [comment]
Hi @svengau, this was a change introduced in `9.x` to expose the `links` and `meta` objects on relationships (which I and many others needed in production). Previously these were stripped from the result. The example snippet in the docs slipped through the cracks and didn't get updated with the output changes.

This change couldn't be done without introducing `data` to the relationships as the [related resource links](https://jsonapi.org/format/#document-resource-object-related-resource-links) (`data.users.links`) are not the same as the [relationship resource links](https://jsonapi.org/format/#document-resource-object-links) (`data.users.data.links`)

`8.x` and below:

```json5
{
  data: {
    id: '1',
    users: {
      type: 'users',
      id: '2',
      slug: 'wopian'
    }
  },
  links: {
    first: 'https://api.example/something?page%5Blimit%5D=10&page%5Boffset%5D=0'
  },
  meta: {
    count: 1
  }
}
```

`9.x` and above:

```json5
{
  data: {
    id: '1',
    links: {
      self: 'https://api.example/something/1'
    },
    users: {
      data: {
        type: 'users',
        id: '2',
        slug: 'wopian',
        links: {
          self: 'https://api.example/users/2'
        }
      },
      links: {
        related: 'https://api.example/something/1/users',
        self: 'https://api.example/something/1/relationships/users'
      }
    }
  },
  links: {
    first: 'https://api.example/something?page%5Blimit%5D=10&page%5Boffset%5D=0'
  },
  meta: {
    count: 1
  }
}

**Comment by svengau** [comment]
oh I understand, thanks for the feedback. sgtm to close this issue.
