### ISSUE TITLE
return the headers with GET respose

### ISSUE THREAD

**Issue by alzizoomar** [wopian/kitsu#575]
i have some data that return in the header object with GET request that i need to access but i didn't found a way to do so, any help?

**Comment by alzizoomar** [comment]
@wopian if you can help, please

**Comment by wopian** [comment]
@wopian is currently on holiday and won't be able to respond to issues until Monday 16th August

**Comment by wopian** [comment]
Response headers are now included in all returns on `10.0.0-alpha.14`, see https://github.com/wopian/kitsu/blob/master/packages/kitsu/MIGRATING.md#response-changes for details (only breaking change is for `api.self`)
