### ISSUE TITLE
Nested same relationships does not deserialize as expected

### ISSUE THREAD

**Issue by BenjaminMINK** [wopian/kitsu#579]
Hello,

Giving the example request below, the deserialization seems to not link relationships as expected except the first one for the same nested relationships (team ID = 1):

```js
api.get('animes/2/episodes', { params: { include: 'teams.artists' } })
```

Returns:

**Note the missing `artists` on the second object**

```
data: [
  {
    type: 'episodes',
    id: '1',
    ...attributes...,
    teams: {
      data: [
        {
          type: 'teams',
          id: '1',
          ...attributes...
          artists: {
            data: [
              {
                 type: 'artists',
                 ...attributes...
              }
            ]
          }
        }
      ]
    }
  },
  {
    type: 'episodes',
    id: '2',
    ...attributes...,
    teams: {
      data: [
        {
          type: 'teams',
          id: '1',
          ...attributes...
        }
      ]
    }
  }
]
```

The API is compliant, and give the expected raw results.

Tested with Kitsu 9 & 10

**Comment by BenjaminMINK** [comment]
If it can helps you, it seems it's related to the deletion of objects after their processing (https://github.com/wopian/kitsu/blob/master/packages/kitsu-core/src/linkRelationships/index.js#L37)

But deleting these objects prevents any processing of the same relationships on another parent object

**Comment by wopian** [comment]
Yeah it seems I made it to clean up after itself as it went, instead of waiting until it had processed the entire document and cleaning the `included`/`relationships` objects at the end. I should be able to get this backported to 9.x without breaking changes.

I'm fairly busy this week, so will try and get some time to work on it.

**Comment by BenjaminMINK** [comment]
Okay, no problem, thanks, good luck! 😀

**Comment by wopian** [comment]
Unfortunately I don't have any updates on this yet.

**Comment by jellylamp** [comment]
This unfortunately hit me as well and makes the entire library unusable. I had to switch to https://github.com/SeyZ/jsonapi-serializer for anyone else in the same boat.

**Comment by wopian** [comment]
A fix has been published in [`10.0.0-alpha.15`](https://github.com/wopian/kitsu/releases/tag/v10.0.0-alpha.25)

**Comment by andrenarchy** [comment]
@wopian Would you be able to backport this to 9.x? Thank you! :raised_hands:

**Comment by wopian** [comment]
> @wopian Would you be able to backport this to 9.x? Thank you! 🙌

Backporting this (and the many other changes it depends on) would unfortunately involve introducing a breaking change in a minor version, please upgrade to [`^10.0.0-alpha.25`](https://github.com/wopian/kitsu/releases/tag/v10.0.0-alpha.25) instead 🙏
