### ISSUE TITLE
Serializing an object with a relationship is not JSONAPI compliant

### ISSUE THREAD

**Issue by dcantu96** [wopian/kitsu#606]
Kitsu v: 10.0.0alpha.17
Hello I am currently having issues serializing an object with a "hasOne" relationship. I noticed this trying to use the kitsu `create` and `update` methods at first. Since the `create` method didn't work, I used the `post` method and that serialized correctly. The `update` had the same problem, however I can't use the `post` method in that case.

To test this I used the `serialise` method like so
`import { serialise } from 'kitsu-core'`
Test object
```
{
  id: "100",
  job: "Chief Implementation Analyst",
  notes: "sdfsdfsdf",
  rfc: "ECÑ870101KD0",
  status: "inactive",
  user: {id: '100', type: 'users'}
}
```
`const serialized = serialise(tableName, data, 'PATCH')`
This is the result
```
"data": {
    "type": "sponsors",
    "id": "100",
    "attributes": {
        "job": "Chief Implementation Analyst",
        "notes": "sdfsdfsdf",
        "rfc": "ECÑ870101KD0",
        "status": "inactive",
        "user": {
            "id": "100",
            "type": "users"
        }
    }
}
```

This is not JSONAPI compliant

It should serialize like this:

```
{
  "data": {
    "type": "sponsors",
    "id": "100",
    "attributes": {
        "job": "Chief Implementation Analyst",
        "notes": "sdfsdfsdf",
        "rfc": "ECÑ870101KD0",
        "status": "inactive"
    },
  "relationships": {
      "user": {
           "data": {
               "id": "100",
               "type": "users"
            }
        }
   }
  }
}
```
[link to JSONAPI crud creating documentation](https://jsonapi.org/format/#crud-creating)

**Comment by dcantu96** [comment]
This is my current work around
```
const { user, id, ...rest } = data
api.axios.patch(`${tableName}/${id}`, {
      data: {
        type: tableName,
        id: id,
        attributes: rest,
        relationships: {
          user: { data: user }
        }
      },
    })
    .then(r => {
      console.log(r)
      history.push(`/${tableName}/${id}`) 
    })
```

**Comment by wopian** [comment]
The examples are no longer valid kitsu-deserialised JSON:API resources in v9*/v10. They must have a `data` object/array which was a required change to support relationship links.

* The serialised->deserialised change happened in v9, but accidentally got released before the deserialised->serialised change got committed

https://github.com/wopian/kitsu/blob/master/packages/kitsu-core/MIGRATING.md#serialising
