### ISSUE TITLE
Cannot call create without attributes

### ISSUE THREAD

**Issue by raldred** [wopian/kitsu#800]
It's currently not possible to call `api.create('anime/1/episodes')` without any additional attributes.
If you do, kitsu refuses to make the request based because of the following code:
https://github.com/wopian/kitsu/blob/master/packages/kitsu-core/src/serialise/index.js#L27

According to the JSON API spec, the `type` member is the only required attribute.
https://jsonapi.org/format/#crud-creating

> The request MUST include a single [resource object](https://jsonapi.org/format/#document-resource-objects) as primary data. The [resource object](https://jsonapi.org/format/#document-resource-objects) MUST contain at least a type member.

It's my understanding as `type` is automatically inferred by kitsu, this means that the following is the only JSON payload required for create.

```
{ 
  data: {
    type: 'episodes'
  }
}
```

Therefore should be to call `api.create('anime/1/episodes')` without any params, or with an empty object `api.create('anime/1/episodes', {})`. 

We're currently having to fudge this by passing a `api.create('anime/1/episodes',  { id: undefined })` (any other junk key would do)

**Comment by pedep** [comment]
I have had the same issue as you, but in my haste i just used the same hack as you.
I think its time for a proper fix #826

**Comment by raldred** [comment]
Lovely, thanks for looking at it.
