### ISSUE TITLE
Fix serialisation validation

### ISSUE THREAD

**Issue by duk3luk3** [wopian/kitsu#84]
In the course of https://github.com/wopian/kitsu/pull/81 it came up that `serialise` doesn't validate data correctly: https://github.com/wopian/kitsu/pull/81#issuecomment-354578586

Do we need different validation logic for different methods (POST/PATCH/PUT?) or is it the same for all?

**Comment by duk3luk3** [comment]
The validation here:

https://github.com/wopian/kitsu/blob/master/src/util/serialise/index.js#L31-L42

is only relevant for `PATCH` and `PUT`, since those are the only methods where you can attach relationships, right?

**Comment by wopian** [comment]
`POST` can also have relationships (the `PUT` method is not used by JSON:API though)

http://jsonapi.org/format/#crud-creating

**Comment by duk3luk3** [comment]
OK, that tells me everything I needed to know I think :-)

I will make a new PR as soon as I find time.
